routes/web.php
<?php

use App\Http\Controllers\ImpersonateController;
use App\Http\Controllers\MenuItemController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/impersonate/stop', [ImpersonateController::class, 'stop'])->name('impersonate.stop');

    Route::middleware(['admin'])->group(function () {
        Route::get('/impersonate/{user}', ImpersonateController::class)->name('impersonate');
        Route::resource('users', UserController::class);
        Route::get('/teams', TeamController::class)->name('teams.index');
        Route::get('/menu-items', MenuItemController::class)->name('menu-items.index');
    });
});

resources/views/table-column/avatar.blade.php
<a href="{{ route('users.show', $row->id) }}">
    <img src="{{ $row->profilePhotoUrl }}" alt="{{ $row->name }}" class="rounded-md h-10 w-10 object-cover" />
</a>

resources/views/table-column/date-time.blade.php
<?php
/**
 * @var Carbon $value
 */

use Carbon\Carbon;
?>

<span data-tooltip-target="tooltip-date-time-{{ $row->id }}">
    {{ $value->diffForHumans() }}
</span>
<x-tooltip id="tooltip-date-time-{{ $row->id }}">
    {{ $value->format('j M') }}
    {{ $value->isCurrentYear() ? '' :  ", {$value->format('Y')}" }}
    {{ $value->format('H:i') }}
</x-tooltip>

resources/views/table-column/team-link.blade.php
<a href="{{ route('teams.show', [$row->id]) }}" class="font-semibold text-indigo-700">
    {{ $value }}
</a>

resources/views/table-column/team.blade.php
{{ $value }}

@if($row->teams->count() > 1)
    <i class="fa fa-user-group text-gray-500 text-xs" data-tooltip-target="tooltip-teams-{{ $row->id }}"></i>
    <x-tooltip id="tooltip-teams-{{ $row->id }}">
        {{ $row->teams->pluck('name')->implode(', ') }}
    </x-tooltip>
@endif

resources/views/table-column/user-actions.blade.php
<span data-tooltip-target="tooltip-impersonate-{{ $row->id }}" class="px-2">
    <a href="{{ route('impersonate', $value)}}">
        <i class="fa fa-sign-in" aria-hidden="true"></i>
    </a>
</span>
<x-tooltip id="tooltip-impersonate-{{ $row->id }}">
    Impersonate
</x-tooltip>

resources/views/table-column/user-name.blade.php
<a href="{{ route('users.show', $row->id) }}" class="font-semibold text-indigo-700">
    {{ $row->name }}
</a>